prefeitura-rio/queries-rj-smtr

- dbt_project.yml
- models/br_rj_riodejaneiro_brt_gps/brt_aux_registros_filtrada.sql
- models/br_rj_riodejaneiro_brt_gps/brt_aux_registros_flag_trajeto_correto.sql
- models/br_rj_riodejaneiro_brt_gps/brt_aux_registros_parada.sql
- models/br_rj_riodejaneiro_brt_gps/brt_aux_registros_velocidade.sql
- models/br_rj_riodejaneiro_veiculos/gps_sppo.sql
Descrição breve:
Ajuste simples das configurações de materialização das tabelas e adiciona parâmetro `brt_id_modal_smtr` que não estava declarado.
> fix(brt/gps): ajusta configurações, adiciona parâmetro faltante 😱

- dbt_project.yml
- models/br_rj_riodejaneiro_brt_gps/brt_aux_registros_flag_trajeto_correto.sql
- models/br_rj_riodejaneiro_brt_gps/brt_aux_registros_parada.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_flag_trajeto_correto.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_parada.sql
Descrição:
Nas tabelas `aux_registros_flag_trajeto_correto` havia uma etapa de filtragem na qual, quando um veículo apresentasse dois sinais simultâneos de gps informando serviços distintos, apenas um era escolhido segundo um critério heurístico. 
Este filtro foi removido e, além disso, foi encontrado um bug nas tabelas `aux_registros_parada` onde, no mesmo caso de sinais simultâneos com serviços distintos, apenas o sinal que tivesse  a menor distância de uma parada/terminal era selecionado. Esse bug também foi corrigido e agora os sinais duplicados não são filtrados e permanecem na tabela tratada final `gps_<modo>`
As tabelas geradas após as modificações estão disponíveis em `rj-smtr-dev`
> fix(gps): remove filtros de seleção de serviço/linha

- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_filtrada.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_flag_trajeto_correto.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_velocidade.sql
- models/br_rj_riodejaneiro_veiculos/gps_sppo.sql
- Remove filtro `datetime_diff` dos modelos `onibus_gps` e `veiculos.gps_sppo`
O tratamento dos dados de gps do SPPO contavam com um filtro para que a diferença maxima permitida entre timestamp_gps e timestamp_captura fosse de 1 minuto. Com os novos parâmetros de captura, estes filtros fazem com que as consultas retornem nenhuma linha. aqui, estes filtros são removidos.
> [smtr][onibus_gps] fix: remove filtros de 1 minuto entre captura e envio

- dbt_project.yml
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_filtrada.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_flag_trajeto_correto.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_realocacao.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_realocacao.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_registros.sql
- models/br_rj_riodejaneiro_veiculos/gps_sppo.sql
Adiciona a etapa de realocação das linhas na materialização dos registros de GPS dos ônibus (SPPO).
- Cria a tabela de realocações válidas por período: `sppo_aux_registros_realocacao`
- Inclui registros realocados na `sppo_aux_registros_filtrada`
- Padroniza tratamento da `linha` em `sppo_registros` para serviço + linha, sem espaçamento
---
Co-authored-by: @eng-rodrigocunha engtransportes.rodrigocunha@gmail.com
Co-authored by:  @Hellcassius caiorogerio.santos@gmail.com
> [onibus_gps] feat: Adiciona realocação de linhas na SPPO

- models/dashboard_subsidio_sppo/sumario_subsidio_dia.sql
- models/projeto_subsidio_sppo/aux_viagem_inicio_fim.sql
- models/projeto_subsidio_sppo/viagem_planejada.sql
- Refatora `trip_id` e `shape_id` de serviço circulares conforme direction_id: _0 para ida, _1 para volta
Extras:
- Incorpora `shape_id_planejado` no `id_viagem`: para tratamento de multiplos shapes planejados (i.e. réveillon), mas ja pode ser extendido para outros casos
- Trata % de KM para datas cujos serviços nao foram planejados: neste ultimo QH vieram entradas com KM total zerada (cujo serviço nao foi planejado para a data). Escolhemos mante-las no planejado, porem nao apurar o valor das mesmas na sumario
> [projeto_subsidio_sppo] Refatora tratamento de viagens circulares (nova versão do GTFS)

- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- models/dashboard_subsidio_sppo/sumario_servico_tipo_viagem_dia.sql
Corrige status duplicado (que consequentemente duplicava a quantidade de viagens) das tabelas `sumario_servico_tipo_viagem_dia` e `sumario_servico_dia_tipo` no model `dashboard_subsidio_sppo`.
> [dashboard_subsidio_sppo] hotfix: corrige status sumario_servico_tipo_viagem_dia + sumario_servico_dia_tipo

- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- models/dashboard_subsidio_sppo/sumario_servico_tipo_viagem_dia.sql
- Insere `distancia_total_planejada > 0 OR distancia_total_planejada IS NOT NULL` para atender ao planejamento de datas anteriores
- Corrige `sumario_servico_tipo_viagem_dia` para não duplicar os serviços planejados em períodos diferentes
> [dashboard_subsidio_sppo] hotfix: sumarios

- models/dashboard_subsidio_sppo/sumario_servico_dia_historico.sql
Altera a ordem das colunas a partir do dia 16-07-2023 para corrigir o bug abaixo:
> hotfix: ordenamento das colunas

- dbt_project.yml
- models/br_rj_riodejaneiro_bilhetagem/gps_validador_van.sql
- models/br_rj_riodejaneiro_bilhetagem/integracao.sql
- models/br_rj_riodejaneiro_bilhetagem/schema.yml
- models/br_rj_riodejaneiro_bilhetagem_staging/gps_validador_aux.sql
- models/dashboard_bilhetagem_implantacao_jae/gps_agregado_brt.sql
- models/dashboard_bilhetagem_implantacao_jae/gps_agregado_onibus.sql
- models/dashboard_bilhetagem_implantacao_jae/gps_agregado_van.sql
- models/dashboard_bilhetagem_implantacao_jae/gps_agregado_vlt.sql
- Separa a tabela de GPS validador em 2 tabelas, uma só para van e outra para os demais modos
- Cria tabelas agregadas para o PBI
> Bilhetagem - Separa tabela de GPS validador van 

- dbt_project.yml
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/staging_linha_sem_ressarcimento.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/staging_ordem_rateio.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/staging_servico_motorista.sql
- models/sources.yml
- bilhetagem.ordem_pagamento:
- feat: Adiciona informações de rateio crédito e débito
- fix: Remove quantidades de rateio crédito e débito da soma do total de transações
- fix: Filtra transações de teste com base na tabela linha_sem_ressarcimento
- cria modelos:
- bilhetagem_staging.linha_sem_ressarcimento_staging
- bilhetagem_staging.ordem_rateio_staging
- bilhetagem_staging.servico_motorista_staging
> Bilhetagem - Adiciona rateio na tabela de ordem de pagamento / ajustes na validação

- models/gtfs/agency_gtfs2.sql
- models/gtfs/calendar_dates_gtfs2.sql
- models/gtfs/calendar_gtfs2.sql
- models/gtfs/fare_attributes_gtfs2.sql
- models/gtfs/fare_rules_gtfs2.sql
- models/gtfs/feed_info_gtfs2.sql
- models/gtfs/frequencies_gtfs2.sql
- models/gtfs/ordem_servico_gtfs2.sql
- models/gtfs/routes_gtfs2.sql
- models/gtfs/schema.yml
- models/gtfs/servicos_sentido2.sql
- models/gtfs/shapes_geom_gtfs2.sql
- models/gtfs/shapes_gtfs2.sql
- models/gtfs/stop_times_gtfs2.sql
- models/gtfs/stops_gtfs2.sql
- models/gtfs/trips_gtfs2.sql
- Ajuste da tabela feed_info para preencher corretamente a coluna feed_end_date
- Alteração das tabelas do gtfs para acrescentar as colunas feed_end_date e feed_version
> 
>
> [WIP] Ajusta tabelas do gtfs para adicionar feed_end_date

- dbt_project.yml
- models/br_rj_riodejaneiro_bilhetagem/CHANGELOG.md
- models/br_rj_riodejaneiro_bilhetagem/schema.yml
- models/dashboard_bilhetagem_implantacao_jae/CHANGELOG.md
- models/dashboard_bilhetagem_implantacao_jae/schema.yml
- Adicionadas descrições das tabelas `ordem_pagamento_consorcio_dia`, `ordem_pagamento_consorcio_operador_dia`, `ordem_pagamento_dia`,`transacao_riocard` e Bilhetagem
- Adicionadas descrições das tabelas `gps_agregado_brt`, `gps_agregado_onibus`, `gps_agregado_van`, `gps_agregado__vlt` de dashboard_bilhetagem_implantacao_jae
> 
>
> Ajusta a descricao das tabelas de bilhetagem

- models/br_rj_riodejaneiro_bilhetagem/CHANGELOG.md
- models/br_rj_riodejaneiro_bilhetagem/integracao.sql
- models/br_rj_riodejaneiro_bilhetagem/transacao.sql
- bilhetagem.transacao
- Limita a quantidade de ids da gratuidade para filtrar
- bilhetagem.transacao e bilhetagem.integracao
- Filtra transações de teste com base nas linhas sem ressarcimento
- Filtra transações com datas anteriores a 2023-07-17
> Bilhetagem - Filtra transação inválidas ou de teste

- models/projeto_subsidio_sppo/CHANGELOG.md
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Adicionado planejamento de Abril/Q2/2024 no modelo `subsidio_data_versao_efetiva.sql`
- Adicionado `2024-04-22` como `Ponto Facultativo` em razão do [`DECRETO RIO Nº 54267/2024`](https://doweb.rio.rj.gov.br/apifront/portal/edicoes/imprimir_materia/1046645/6539)
- Corrigido e refatorado o tratamento do modelo `subsidio_data_versao_efetiva.sql`
> Adicionado planejamento de Abril/Q2/2024 no modelo `subsidio_data_versao_efetiva.sql`

- models/projeto_subsidio_sppo/CHANGELOG.md
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Adicionado planejamento de Maio/Q1/2024 no modelo `subsidio_data_versao_efetiva.sql`
- Adicionado planejamento específico de `2024-05-04` e `2024-05-05` em razão do evento "Madonna · The Celebration Tour in Rio" (Processo Rio MTR-PRO-2024/06338) no modelo `subsidio_data_versao_efetiva.sql`
- Corrigido tratamento do modelo `subsidio_data_versao_efetiva.sql`
> Adiciona planejamento de Maio/Q1/2024 + Corrige tratamento `subsidio_data_versao_efetiva.sql`

- models/projeto_subsidio_sppo/CHANGELOG.md
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Removido planejamento específico de `2024-05-04` e `2024-05-05` em razão do evento "Madonna · The Celebration Tour in Rio" (Processo Rio MTR-PRO-2024/06338) no modelo `subsidio_data_versao_efetiva.sql`
> Remove planejamento específico do evento "Madonna" no modelo `subsidio_data_versao_efetiva.sql`

- models/dashboard_subsidio_sppo/CHANGELOG.md
- models/dashboard_subsidio_sppo/viagens_remuneradas.sql
- Corrigido filtro da CTE `viagens_planejadas` no modelo `viagens_remuneradas.sql`
> Corrige filtro da CTE `viagens_planejadas` no modelo `viagens_remuneradas.sql` 

- models/gtfs/CHANGELOG.md
- models/gtfs/ordem_servico_gtfs.sql
- models/gtfs/ordem_servico_trajeto_alternativo_gtfs.sql
- Adiciona coluna `tipo_os` no modelo `ordem_servico_trajeto_alternativo_gtfs.sql`
- Corrige tratamento da coluna `tipo_os` do modelo `ordem_servico_gtfs.sql`
> [gtfs] Adiciona e corrige tratamento coluna `tipo_os`

- macros/get_last_feed_start_date.sql
- models/gtfs/CHANGELOG.md
- models/gtfs/agency_gtfs.sql
- models/gtfs/calendar_dates_gtfs.sql
- models/gtfs/calendar_gtfs.sql
- models/gtfs/fare_attributes_gtfs.sql
- models/gtfs/fare_rules_gtfs.sql
- models/gtfs/frequencies_gtfs.sql
- models/gtfs/routes_gtfs.sql
- models/gtfs/shapes_geom_gtfs.sql
- models/gtfs/shapes_gtfs.sql
- models/gtfs/stop_times_gtfs.sql
- models/gtfs/stops_gtfs.sql
- models/gtfs/trips_gtfs.sql
- Corrige atualização incremental da coluna `feed_end_date` nos modelos:
- `agency_gtfs.sql`
- `calendar_dates_gtfs.sql`
- `fare_attributes_gtfs.sql`
- `fare_rules_gtfs.sql`
- `frequencies_gtfs.sql`
- `routes_gtfs.sql`
- `shapes_geom_gtfs.sql`
- `shapes_gtfs.sql`
- `stop_times_gtfs.sql`
- `stops_gtfs.sql`
- `trips_gtfs.sql`
> Hotfix - Corrige atualização da coluna feed_end_date nas tabelas do GTFS

- models/br_rj_riodejaneiro_rdo/CHANGELOG.md
- models/br_rj_riodejaneiro_rdo/rdo40_registros.sql
- models/projeto_subsidio_sppo_encontro_contas/CHANGELOG.md
- models/projeto_subsidio_sppo_encontro_contas/aux_balanco_rdo_servico_dia.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_servico_dia.sql
- Corrige apontamento da tabela de parâmetros para a `projeto_subsidio_sppo_encontro_contas.parametros_km`. Estava apontando para a tabela de um dataset de teste.
TODO:
> Hotfix: Corrige apontamento da tabela de `parametros_km` do encontro de contas

- dbt_project.yml
Corrige variável `data_versao_gtfs` para não ocasionar quebra da action do dbt docs
> [hotfix] Corrige variável `data_versao_gtfs`

- models/projeto_subsidio_sppo/CHANGELOG.md
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Adicionados feriado de Corpus Christi (2024-05-30) e Ponto Facultativo (2024-05-31) no modelo `subsidio_data_versao_efetiva`
> 
>
> adiciona feriado de corpus christi  e ponto facultativo em subsidio_data_versao_efetiva

- models/br_rj_riodejaneiro_bilhetagem/CHANGELOG.md
- models/br_rj_riodejaneiro_bilhetagem/passageiros_hora.sql
- Adiciona transações de ônibus a partir do dia `2024-04-19` no modelo `passageiros_hora.sql`
> Bilhetagem - adiciona transações de ônibus na passageiros_hora

- dbt_project.yml
- models/projeto_subsidio_sppo_encontro_contas/CHANGELOG.md
- models/projeto_subsidio_sppo_encontro_contas/aux_balanco_rdo_servico_dia.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_consorcio_ano.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_consorcio_dia.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_servico_ano.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_servico_dia.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_servico_dia_pos_gt.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_servico_dia_pre_gt.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_servico_quinzena.sql
- models/projeto_subsidio_sppo_encontro_contas/receita_tarifaria_servico_nao_identificado_quinzena.sql
- models/projeto_subsidio_sppo_encontro_contas/schema.yml
- models/projeto_subsidio_sppo_encontro_contas/staging/rdo_correcao_rioonibus_servico_quinzena.sql
- models/sources.yml
- Adiciona modelo `staging.rdo_correcao_rioonibus_servico_quinzena.sql`
- Adiciona modos de execução `""` (antes das alterações do Grupo de Trabalho) e `"_pos_gt"` (após as alterações do Grupo de Trabalho) conforme Processo.Rio MTR-PRO-2024/06270 e as respectivas alterações dos nomes das tabelas
- Adiciona novo tratamento de serviços do RDO no modelo `balanco_servico_dia_pos_gt.sql` com base no modelo `balanco_servico_dia.sql`
- Adiciona e altera descrições no schema.yml dos modelos
> Altera tratamento do RDO no Encontro de Contas

- models/dashboard_subsidio_sppo/CHANGELOG.md
- models/dashboard_subsidio_sppo/viagens_remuneradas.sql
- models/projeto_subsidio_sppo/CHANGELOG.md
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Altera critérios para o `indicador_viagem_remunerada` no modelo `viagens_remuneradas.sql`, de forma a ser indicado como nulo em caso de falha na união de tabelas
- Altera lógica do modelo `subsidio_data_versao_efetiva.sql`, de forma a considerar por regra sempre o mesmo intervalo de datas do modelo `feed_info_gtfs.sql`
> Altera tratamento nos modelos `viagens_remuneradas.sql` + `subsidio_data_versao_efetiva.sql`
