prefeitura-rio/queries-rj-smtr

- models/projeto_subsidio_sppo/aux_registros_status_trajeto.sql
- models/projeto_subsidio_sppo/aux_viagem_registros.sql
- models/projeto_subsidio_sppo/viagem_completa.sql
- Ajusta queries de D-2 para D-1
> 
>
> fix: set run date to D-1 

- LICENSE
- dbt_project.yml
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_flag_trajeto_correto.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_registros.sql
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- models/projeto_subsidio_sppo/subsidio_shapes_geom.sql
- models/projeto_subsidio_sppo/sumario_subsidio_dia_periodo.sql
- models/projeto_subsidio_sppo/viagem_planejada.sql
- Altera queries de D-2 para D-1
- Adiciona feriados de setembro (hardcode)
- Adiciona data versao das tabelas de planejamento
> 
>
> [smtr][subsidio_sppo] fix: set run date to D-1

- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Adiciona datas de planejamento dos dias 1 e 2/10 para seguirem o planejado da última quinzena de setembro
> Altera planejado das eleicoes

- models/projeto_subsidio_sppo/registros_status_viagem.sql
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- models/projeto_subsidio_sppo/subsidio_shapes_geom.sql
- models/projeto_subsidio_sppo/viagem_completa.sql
- models/projeto_subsidio_sppo/viagem_conformidade.sql
- models/projeto_subsidio_sppo/viagem_planejada.sql
- Adiciona configuração para deletar e sobrescrever dados de tabela materializadas com base nas `unique_keys`
- Adiciona feriado de outubro na `data_efetiva` do subsidio
> Adiciona `insert_overwrite` às materializações do subsídio

- .gitignore
- README.md
- dbt_project.yml
- dev/profiles-example.yml
- dev/run.py
- dev/utils.py
- models/br_rj_riodejaneiro_onibus_gps/schema.yaml
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_filtrada.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_aux_registros_realocacao.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_realocacao.sql
- models/br_rj_riodejaneiro_onibus_gps/sppo_registros.sql
- models/br_rj_riodejaneiro_veiculos/gps_sppo.sql
- Adiciona pipeline de realocação das linhas de ônibus (`onibus_gps.[...]` + `gps_sppo`)
- Adiciona instruções para desenvolvimento local (`dev/` + `README.md`)
> [deploy][onibus_gps] Pipeline de realocação

- models/br_rj_riodejaneiro_onibus_gps/schema.yaml
- Remove os testes do schema da onibus_gps
> fix: remove tests from onibus_gps schema

- dbt_project.yml
- models/dashboard_subsidio_sppo/sumario_subsidio_dia.sql
- models/dashboard_subsidio_sppo/sumario_subsidio_dia_periodo.sql
- models/dashboard_subsidio_sppo/viagens_realizadas.sql
- Altera data da run para a mesma data limite observada na tabela: https://github.com/prefeitura-rio/pipelines/pull/324
> [dash_subsidio_sppo] Ajusta parâmetro de data da pipeline

- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Alteração de nome de atributo da tabela `subsidio_data_versao_efetiva`.
> [projeto_subsidio_sppo] hotfix: alteração de nome de atributo

- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Inclusão de informações adicionais na tabela `subsidio_data_versao_efetiva`.
> [projeto_subsidio_sppo] hotfix: complementações subsidio_data_versao_efetiva

- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Incorpora feriados na tabela `subsidio_data_versao_efetiva`
> [subsidio_sppo] fix: feriados

- dbt_project.yml
- models/operacao/sppo_infracao.sql
- models/operacao/sppo_veiculo_dia.sql
- models/veiculo/sppo_licenciamento.sql
Tabelas temporárias até a finalização das mudanças do subsídio (licenciamento e operacao via pipelines)
> [SPPO] adiciona views de operacao + licenciamento 

- models/br_rj_riodejaneiro_rdo/rho_registros_sppo.sql
- Altera os parâmetros da rho_registros_sppo
> Hotfix: Update rho_registros_sppo vars

- dbt_project.yml
- models/dashboard_subsidio_sppo/sumario_servico_tipo_viagem_dia.sql
Tabela pedida pela equipe de dashboard de kms + viagens por servico e tipo da viagem. Será atualizada a cada quinzena
> [dashboard_subsidio_sppo] Adiciona tabela do dash subsidio v2

- README.md
- requirements-dev.txt
- inclusão da atualização do pipe no readme para conseguir instalar corretamente os pacotes.
- inclusão no requirements-dev.txt dos pacotes pandas e devtools.
> fix: ajustes no readme e nos pacotes instalados

- models/veiculo/sppo_veiculo_dia.sql
Altera parâmetro para considerar infrações em D+7
> [veiculo] hotfix: altera parâmetro para D+7

- models/veiculo/sppo_veiculo_dia.sql
Altera parâmetro para considerar a próxima partição disponível, caso a exata data não estiver disponível (provável falha de captura)
> [veiculo][sppo_veiculo_dia] Altera parâmetro para considerar a próxima partição disponível

- models/veiculo/sppo_licenciamento.sql
Atualização de parâmetros da `sppo_licenciamento` para compatibilização com demais tabelas
> [projeto_subsidio_sppo][sppo_licenciamento] Atualização de parâmetros para compatibilização com demais tabelas

- models/veiculo/sppo_licenciamento.sql
Corrige referência na `sppo_licenciamento_stu`.
> [veiculo][sppo_licenciamento_stu] hotfix: referência de tabela

- .gitignore
Altera .gitignore para ignorar arquivos na pasta `dev`
> Altera .gitignore para ignorar arquivos na pasta dev

- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- models/dashboard_subsidio_sppo/sumario_servico_tipo_viagem_dia.sql
Corrige os `status`/`tipo_viagem` de tabelas do model `dashboard_subsidio_sppo`.
> [dashboard_subsidio_sppo] hotfix: tipos de viagem

- models/dashboard_subsidio_sppo/sumario_servico_tipo_viagem_dia.sql
Atualiza status `sumario_servico_tipo_viagem_dia` no `dashboard_subsidio_sppo` conforme relação mais atualizada de status.
> [dashboard_subsidio_sppo] Atualiza status sumario_servico_tipo_viagem_dia

- models/dashboard_subsidio_sppo/sumario_servico_dia.sql
- models/dashboard_subsidio_sppo/sumario_servico_tipo_viagem_dia.sql
Corrige arredondamentos e referências das tabelas `sumario_servico_dia` e `sumario_servico_tipo_viagem_dia`.
> [dashboard_subsidio_sppo] hotfix sumarios

- models/dashboard_subsidio_sppo/sumario_servico_tipo_viagem_dia.sql
Corrige arredondamento da tabela `sumario_servico_tipo_viagem_dia`
> [dashboard_subsidio_sppo] Corrige arredondamento sumario_servico_tipo_viagem_dia

- models/dashboard_subsidio_sppo/sumario_servico_dia_historico.sql
- Atualização da tabela `sumario_servico_dia_historico` com novas regras após nova decisão judicial
> Atualização da tabela `sumario_servico_dia_historico`

- dbt_project.yml
- models/dashboard_subsidio_sppo/subsidio_ordem_servico.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia.sql
- Adiciona regra de 120% na `sumario_servico_dia` conforme RESOLUÇÃO SMTR Nº 3645/2023
> Adiciona regra de 120% - `sumario_servico_dia` - RESOLUÇÃO SMTR Nº 3645/2023

- models/dashboard_subsidio_sppo/subsidio_ordem_servico.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia.sql
- models/dashboard_subsidio_sppo/viagens_remuneradas.sql
- Altera estrutura de tabelas do dataset `dashboard_subsidio_sppo` para inclusão da regra de 120% conforme RESOLUÇÃO SMTR Nº 3645/2023
- Incorpora aplicação de novas regras apenas a partir de `2023-09-16`
> Altera estrutura `dashboard_subsidio_sppo` com regra de 120%

- models/br_rj_riodejaneiro_bilhetagem/transacao.sql
> Hotfix filtro data transação

- models/dashboard_subsidio_sppo/subsidio_ordem_servico.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia.sql
- models/dashboard_subsidio_sppo/viagens_remuneradas.sql
- Atualiza regras para atender à RESOLUÇÃO SMTR Nº 3645/2023
> hotfix: Regra 120%

- models/br_rj_riodejaneiro_gtfs/ordem_servico_diaria.sql
- models/br_rj_riodejaneiro_gtfs/servicos_sentido.sql
- models/br_rj_riodejaneiro_gtfs/shapes_geom_gtfs.sql
- Refatora shapes_geom
- Adiciona:
- ordem_servico_diaria: ordem_servico por dia
- servicos_sentido: sentidos de cada serviço
> [gtfs] Refatora shapes_geom + Adiciona ordem_servico_diaria + servicos_sentido

- models/br_rj_riodejaneiro_veiculos/gps_brt_15_minutos.sql
Adiciona tabela `gps_brt_15_minutos`.
> [gps_brt] Adiciona tabela `gps_brt_15_minutos`

- models/projeto_subsidio_sppo/aux_registros_status_trajeto.sql
> Corrige serviços noturnos

- models/dashboard_subsidio_sppo/viagens_remuneradas.sql
Realiza hotfix na tabela `viagens_remuneradas` de forma a considerar qualquer `data_versao` de ordem de serviço no mês.
> [subsidio_sppo] hotfix: viagens remuneradas

- models/dashboard_subsidio_sppo/subsidio_parametros.sql
- models/dashboard_subsidio_sppo/viagens_remuneradas.sql
Materialização `subsidio_parametros`.
> hotfix: materialização `subsidio_parametros`

- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento.sql
- remove linha consorcio da tabela ordem_pagamento
> remove linha consorcio da tabela ordem_pagamento

- dev/utils.py
- models/br_rj_riodejaneiro_gtfs/ordem_servico_diaria.sql
- models/br_rj_riodejaneiro_gtfs/ordem_servico_viagens_planejadas.sql
Atualiza `ordem_servico_diaria` e cria `ordem_servico_viagens_planejadas`.
> Atualiza `ordem_servico_diaria` e cria `ordem_servico_viagens_planejadas`

- models/br_rj_riodejaneiro_gtfs/ordem_servico_diaria.sql
Adiciona tratamento para novos `tipo_dia` em `ordem_servico_diaria`.
> Adiciona tratamento para novos `tipo_dia` em `ordem_servico_diaria`

- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
Adiciona calendário 2024 na tabela `subsidio_data_versao_efetiva`
> Adiciona calendário 2024

- dbt_project.yml
- models/dashboard_subsidio_sppo/subsidio_parametros.sql
- models/veiculo/sppo_registro_agente_verao.sql
- models/veiculo/sppo_veiculo_dia.sql
Adiciona registros de Agentes de Verão para fins de cálculo de subsídio nos termos da RESOLUÇÃO SMTR Nº 3.682/2024.
> Adiciona registros de Agentes de Verão

- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
Hotfix da tabela `sumario_servico_dia_tipo`
> hotfix `sumario_servico_dia_tipo`

- models/veiculo/schema.yml
- models/veiculo/sppo_registro_agente_verao.sql
**Hotfix:** tabela `sppo_registro_agente_verao`:
- Manter sempre o datetime_captura
- Muda nome da coluna datetime_captura 
- Adiciona coluna versao
> Hotfix: Tabela `sppo_registro_agente_verao`

- models/dashboard_subsidio_sppo/sumario_servico_tipo_viagem_dia.sql
Hotfix `sumario_servico_tipo_viagem_dia`
> Hotfix `sumario_servico_tipo_viagem_dia`

- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo_sem_glosa.sql
Hotfix `sumario_servico_dia_tipo` e `sumario_servico_dia_tipo_sem_glosa`
> Hotfix `sumario_servico_dia`

- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo_sem_glosa.sql
> Hotfix sumario dia tipo

- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo_sem_glosa.sql
Corrige coluna da tabela `sumario_servico_dia_tipo_sem_glosa`
> Corrige coluna da tabela `sumario_servico_dia_tipo_sem_glosa`

- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo_sem_glosa.sql
Insere status na `sumario_servico_dia_tipo_sem_glosa`
> Insere status na `sumario_servico_dia_tipo_sem_glosa`

- models/br_rj_riodejaneiro_bilhetagem/passageiros_hora.sql
- models/br_rj_riodejaneiro_bilhetagem/schema.yml
- models/br_rj_riodejaneiro_bilhetagem/transacao.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/gratuidade_aux.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/staging_gratuidade.sql
- models/br_rj_riodejaneiro_rdo/rho_registros_sppo.sql
- models/br_rj_riodejaneiro_rdo/rho_registros_stpl.sql
- models/br_rj_riodejaneiro_rdo_staging/rho_registros_stpl_aux.sql
- models/sources.yml
- Adiciona tipo da gratuidade na tabela transação
- Materializa tabela passageiros_hora
- Corrige logica de busca por partição no RHO
> Bilhetagem Jaé - Adiciona tipo da gratuidade e materializa passageiros_hora

- models/br_rj_riodejaneiro_bilhetagem/passageiros_hora.sql
- Adiciona filtro para retirar partições nulas do filtro da passageiros_hora
> [HOTFIX] Corrige busca por nula no modelo passageiros_hora

- models/br_rj_riodejaneiro_bilhetagem/passageiros_hora.sql
- Filtrar apenas transações no BRT na passageiros hora
- Remove transações com o tipo transação nulo
> Bilhetagem - Filtrar apenas dados de BRT na tabela passageiros_hora

- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
Refatora `subsidio_data_versao_efetiva` para garantir sempre o uso da última versão disponível
> Refatora `subsidio_data_versao_efetiva`

- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
Altera calendário incluindo datas de março na `subsidio_data_versao_efetiva`
> Altera calendário incluindo datas de março na tabela `subsidio_data_versao_efetiva`

- models/br_rj_riodejaneiro_bilhetagem/passageiros_hora.sql
- bilhetagem.passageiros_hora
-  Altera a coluna tipo_transacao_detalhe_smtr para transações de Transferência do tipo do pagamento para "Transferência"
> Bilhetagem - Alterar tipo_transacao_detalhe_smtr para transações de Transferência

- dev/run.py
> Adiciona run.py

- dbt_project.yml
- models/br_rj_riodejaneiro_bilhetagem/integracao.sql
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento.sql
- models/br_rj_riodejaneiro_bilhetagem/passageiros_hora.sql
- models/br_rj_riodejaneiro_bilhetagem/schema.yml
- models/br_rj_riodejaneiro_bilhetagem/transacao.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/staging_linha.sql
- models/cadastro/schema.yml
- models/cadastro/servicos.sql
- models/cadastro_staging/servicos_gtfs_aux.sql
- models/dashboard_bilhetagem_jae/schema.yml
- models/dashboard_bilhetagem_jae/view_integracao.sql
- models/dashboard_bilhetagem_jae/view_passageiros_hora.sql
- bilhetagem.passageiros_hora, bilhetagem.transacao, bilhetagem.integracao:
- altera serviço para id da jae
- Cria tabela cadastro.servicos
- Cria views para o dashboard  
- bilhetagem.ordem_pagamento:
- cria filtro de data processamento para transações capturadas meia noite
> Liga linhas e estações da Jaé com o GTFS, Ajusta filtro de transações da ordem_pagamento 

- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento_consorcio_dia.sql
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento_consorcio_operador_dia.sql
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento_dia.sql
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento_servico_operador_dia.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/staging_ordem_pagamento_consorcio.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/staging_ordem_pagamento_consorcio_operadora.sql
- models/sources.yml
- Cria modelos ordem_pagamento agregados em diferentes níveis, seguindo o padrão da Jaé
> Bilhetagem - Cria tabelas agregadas de ordem de pagamento da Jaé 

- dbt_project.yml
- models/br_rj_riodejaneiro_onibus_gps_zirix/CHANGELOG.md
- models/br_rj_riodejaneiro_onibus_gps_zirix/gps_sppo_zirix.sql
- models/br_rj_riodejaneiro_onibus_gps_zirix/schema.yaml
- models/br_rj_riodejaneiro_onibus_gps_zirix/sppo_aux_registros_filtrada_zirix.sql
- models/br_rj_riodejaneiro_onibus_gps_zirix/sppo_aux_registros_flag_trajeto_correto_zirix.sql
- models/br_rj_riodejaneiro_onibus_gps_zirix/sppo_aux_registros_parada_zirix.sql
- models/br_rj_riodejaneiro_onibus_gps_zirix/sppo_aux_registros_realocacao_zirix.sql
- models/br_rj_riodejaneiro_onibus_gps_zirix/sppo_aux_registros_velocidade_zirix.sql
- models/br_rj_riodejaneiro_onibus_gps_zirix/sppo_realocacao_zirix.sql
- models/br_rj_riodejaneiro_onibus_gps_zirix/sppo_registros_zirix.sql
- models/sources.yml
- Criação de copia da `onibus_gps` e `gps_sppo` para a API da zirix
> 
>
> Cria o tratamento do gps_sppo da API da Zirix

- models/veiculo/sppo_licenciamento.sql
- models/veiculo/sppo_veiculo_dia.sql
Fixa data de licenciamento - mar/Q2
> Fixa data de licenciamento - mar/Q2

- models/br_rj_riodejaneiro_onibus_gps_zirix/CHANGELOG.md
- models/br_rj_riodejaneiro_onibus_gps_zirix/sppo_realocacao_zirix.sql
- Converte colunas de data e hora do modelo `onibus_gps_zirix.sppo_realocacao_zirix` para o tipo adequado
> [HOTFIX] Ajusta colunas data e hora da view sppo_realocacao da Zirix

- models/veiculo/CHANGELOG.md
- models/veiculo/sppo_registro_agente_verao.sql
- models/veiculo/staging/sppo_registro_agente_verao_staging.sql
- veiculo.sppo_registro_agente_verao
- Cria deduplicação dos dados de staging
> [HOTFIX] Cria deduplicacao na tabela sppo_registro_agente_verao

- dev/run.py
> Adiciona dev/run.py

- models/cadastro/CHANGELOG.md
- models/cadastro/consorcios.sql
- models/cadastro/schema.yml
- models/sources.yml
- Adicionada coluna de modo na tabela `cadastro.consorcio`
- Adicionadas descrições das colunas modo e razão social no schema
- Adicionado source para `cadastro_staging.consorcio_modo`
> 
>
> Adiciona coluna modo em cadastro.consorcio

- models/dashboard_subsidio_sppo/CHANGELOG.md
- models/dashboard_subsidio_sppo/sumario_servico_dia.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- models/dashboard_subsidio_sppo/viagens_remuneradas.sql
- models/gtfs/CHANGELOG.md
- models/gtfs/ordem_servico_trips_shapes_gtfs2.sql
- models/projeto_subsidio_sppo/CHANGELOG.md
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Adicionados filtros nos modelos `sumario_servico_dia_tipo.sql`, `sumario_servico_dia.sql` e `viagens_remuneradas.sql` em razão de alterações no modelo `viagem_planejada.sql`
- Corrigido modelo `viagens_remuneradas.sql` em razão de alterações nos modelos `subsidio_data_versao_efetiva.sql` e `ordem_servico_gtfs2.sql`
- Corrige tratamento por partição do modelo `ordem_servico_trips_shapes_gtfs2.sql`
- Corrigido tratamento do modelo `subsidio_data_versao_efetiva.sql`
> Corrige e refatora modelos em `dashboard_subsidio_sppo`, `gtfs` e `projeto_subsidio_sppo`

- models/projeto_subsidio_sppo_encontro_contas/aux_balanco_rdo_servico_dia.sql
- models/projeto_subsidio_sppo_encontro_contas/balanco_servico_quinzena.sql
- models/projeto_subsidio_sppo_encontro_contas/receita_tarifaria_servico_nao_identificado_quinzena.sql
- models/projeto_subsidio_sppo_encontro_contas/schema.yml
- Atualiza nomes de tabelas e colunas
- Adiciona `schema.yml` com descrição de tabelas e colunas
> Atualiza schema do encontro contas

- dbt_project.yml
- models/br_rj_riodejaneiro_bilhetagem/CHANGELOG.md
- models/br_rj_riodejaneiro_bilhetagem/gps_validador.sql
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento_consorcio_dia.sql
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento_consorcio_operador_dia.sql
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento_dia.sql
- models/br_rj_riodejaneiro_bilhetagem/ordem_pagamento_servico_operador_dia.sql
- models/br_rj_riodejaneiro_bilhetagem/schema.yml
- models/br_rj_riodejaneiro_bilhetagem/transacao.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/gps_validador_aux.sql
- models/br_rj_riodejaneiro_bilhetagem_staging/staging_gps_validador.sql
- models/cadastro/CHANGELOG.md
- models/validacao_dados_jae/CHANGELOG.md
- models/validacao_dados_jae/integracao_invalida.sql
- models/validacao_dados_jae/ordem_pagamento_validacao.sql
- models/validacao_dados_jae/schema.yml
- models/validacao_dados_jae/staging/ordem_pagamento_consorcio_dia_validacao.sql
- models/validacao_dados_jae/staging/ordem_pagamento_consorcio_operador_dia_validacao.sql
- models/validacao_dados_jae/staging/ordem_pagamento_servico_operador_dia_validacao.sql
- models/validacao_dados_jae/transacao_invalida.sql
- models/validacao_dados_jae/veiculo_validacao.sql
- Criação dos modelos para validação dos dados da Jaé :
- **validacao_dados_jae_staging**:
- `ordem_pagamento_consorcio_dia_validacao.sql`
- `ordem_pagamento_consorcio_operador_dia_validacao.sql`
- `ordem_pagamento_servico_operador_dia_validacao.sql`
- **validacao_dados_jae**:
- `integracao_invalida.sql`
- `ordem_pagamento_validacao.sql`
- `transacao_invalida.sql`
- `veiculo_validacao.sql`
- Adiciona tratamento da coluna id_veiculo nos modelos ` transacao.sql` e `gps_validador.sql`
-  Adiciona coluna `quantidade_total_transacao` nos modelos `ordem_pagamento_consorcio_dia.sql`, `ordem_pagamento_consorcio_operador_dia.sql` e `ordem_pagamento_dia.sql`
- Remove validação do modelo `ordem_pagamento_servico_operador_dia.sql`
- Corrige arquivos de changelog dos datasets …
> Bilhetagem - Validação dados da Jaé

- models/validacao_dados_jae/CHANGELOG.md
- models/validacao_dados_jae/ordem_pagamento_validacao.sql
- models/validacao_dados_jae/staging/ordem_pagamento_consorcio_dia_validacao.sql
- Corrige variável de data no modelo `ordem_pagamento_consorcio_dia_validacao.sql`
- Corrige referências nos modelos `ordem_pagamento_consorcio_dia_validacao.sql` e `ordem_pagamento_validacao.sql`
> Hotfix - corrige referencias e variavel de data na validação da Jaé

- models/projeto_subsidio_sppo/CHANGELOG.md
- models/projeto_subsidio_sppo/subsidio_data_versao_efetiva.sql
- Adicionados feriado de Corpus Christi (2024-05-30) e Ponto Facultativo (2024-05-31) no modelo `subsidio_data_versao_efetiva`
> adiciona feriado de corpus christi e ponto facultativo em subsidio_data_versao_efetiva

- models/dashboard_subsidio_sppo/CHANGELOG.md
- models/dashboard_subsidio_sppo/sumario_servico_dia_historico.sql
- models/dashboard_subsidio_sppo/sumario_servico_dia_tipo.sql
- Altera materialização dos modelos `sumario_servico_dia_historico.sql` e `sumario_servico_dia_tipo.sql` de view para incremental
> Subsidio - Materializa tabelas sumario_servico_dia_historico e sumario_servico_dia_tipo
